{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: avalanche
  namespace: {{ .Values.namespace.name }}

spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      name: http-avalanche
  type: {{ .Values.service.type }}
  {{- with .Values.service.clusterIP }}
  clusterIP: {{ . }}
  {{- end }}
  selector:
    app: avalanche
{{- end }}