namespace:
  name: monitoring

replicaCount: 1
image:
  repository: quay.io/prometheuscommunity/avalanche
  tag: latest

remoteWriteUrl: "http://cortex-distributor.cortex.svc.cluster.local:8080/api/v1/push"

service:
  enabled: true
  port: 9001
  type: ClusterIP
  clusterIP: None

# Metrics generation configuration
metrics:
  gaugeCount: 16
  counterCount: 28
  histogramCount: 2
  histogramBuckets: 10
  nativeHistogramCount: 0
  summaryCount: 5
  summaryObjectives: 2
  seriesCount: 10
  valueInterval: 300
  seriesInterval: 3600
  metricInterval: 0

resources:
  requests:
    cpu: "500m"
    memory: "512Mi"
  limits:
    cpu: "1000m"
    memory: "1Gi"