# Keycloak Admin User Configuration
auth:
  adminUser: admin
  adminPassword: admin

# PostgreSQL Specific Configuration
# U can also configure external database like RDS Postgres  using externalDatabse value: 
# https://artifacthub.io/packages/helm/bitnami/keycloak?modal=values&path=externalDatabase

postgresql:
  enabled: true
  auth:
    username: bn_keycloak
    password: bn_keycloak
    database: bitnami_keycloak

# Kubernetes Service Configuration
service:
  type: NodePort
  nodePorts:
    http: 30080

# Additional Keycloak Environment Variables
extraEnvVars:
  - name: KC_PRODUCTION
    value: "true"
  - name: KC_HOSTNAME_STRICT
    value: "false"
  - name: KC_HTTP_ENABLED
    value: "true"
  - name: VERTX_WORKER_POOL_SIZE
    value: "20"
  - name: VERTX_EVENT_LOOP_POOL_SIZE
    value: "8"
