grafana:
  adminPassword: prom-operator
  persistence:
    enabled: true
    size: 10Gi
  additionalDataSources:
    - name: Cortex
      type: prometheus
      access: proxy
      url: http://cortex-query-frontend.cortex.svc.cluster.local:8080/api/prom
      isDefault: false
      jsonData:
        httpHeaderName1: "X-Scope-OrgID"
      secureJsonData:
        httpHeaderValue1: "anonymous"
    # - name: Loki
    #   type: loki
    #   access: proxy
    #   url: http://loki-query-frontend.loki.svc.cluster.local:3100
    #   isDefault: false
    #   jsonData:
    #     maxLines: 1000       # optional: increases the number of lines per query result
      
prometheusOperator:
  createCustomResource: true

prometheus:
  prometheusSpec:
    remoteWrite:
      - url: http://cortex-distributor.cortex.svc.cluster.local:8080/api/v1/push
    retention: 10d
    resources:
      requests:
        memory: 1Gi
        cpu: 500m
      limits:
        memory: 2Gi

alertmanager:
  alertmanagerSpec:
    retention: 120h
    
